### ISSUE TITLE
still not working in version 10

### ISSUE THREAD

**Issue by sirbooker** [jrhubott/homeseer#2]
i also know of another member with the same issues

Logger: homeassistant.config_entries
Source: custom_components/homeseer/__init__.py:140
First occurred: 9:12:56 AM (1 occurrences)
Last logged: 9:12:56 AM

Error setting up entry Homeseer for homeseer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/homeseer/__init__.py", line 140, in async_setup_entry
    await homeseer.api.initialize()
  File "/usr/local/lib/python3.8/site-packages/pyhs3ng/hometroller.py", line 64, in initialize
    await self._get_devices()
  File "/usr/local/lib/python3.8/site-packages/pyhs3ng/hometroller.py", line 119, in _get_devices
    all_devices = result["Devices"]
KeyError: 'Devices'

**Comment by Tipalo** [comment]
Greetings,
I have the same error here. This has been a persistent error since my first attempt at installing over a week ago. Unlike @sirbooker, I have never had any luck showing any entities on the integration screen.

Logger: homeassistant.config_entries
Source: custom_components/homeseer/__init__.py:140
First occurred: February 14, 2021, 10:03:32 PM (1 occurrences)
Last logged: February 14, 2021, 10:03:32 PM

Error setting up entry Homeseer for homeseer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/homeseer/__init__.py", line 140, in async_setup_entry
    await homeseer.api.initialize()
  File "/usr/local/lib/python3.8/site-packages/pyhs3ng/hometroller.py", line 64, in initialize
    await self._get_devices()
  File "/usr/local/lib/python3.8/site-packages/pyhs3ng/hometroller.py", line 119, in _get_devices
    all_devices = result["Devices"]
KeyError: 'Devices'

![Cap1](https://user-images.githubusercontent.com/55360416/107981640-51da8980-6f77-11eb-8169-43bcf3719bb2.PNG)

Not sure if this is relevant but digging around found this typo:
![Cap2](https://user-images.githubusercontent.com/55360416/107981450-ee505c00-6f76-11eb-89aa-813575d91399.PNG)

**Comment by sirbooker** [comment]
![hs4-ha](https://user-images.githubusercontent.com/16746210/107982336-b0ecce00-6f78-11eb-9979-f1eaff3f1e88.png)

**Comment by jrhubott** [comment]
What version of homeseer are you using?  Maybe something is different in the message structure returned.

**Comment by sirbooker** [comment]
homeseer V4.1.11.0

**Comment by jrhubott** [comment]
This component is only for HS3 and has not been tested with HS4 as I decided to move to Home Assistant rather then HS4.  I just use HS3 for ZWave / Insteon / DSC.

The structure returned must have changed for HS4.  I don't intend to support HS4 as I don't have anyway to test it.

**Comment by sirbooker** [comment]
Ok, thanks.
just an fyi   it did work to start but then trying to update from 1.04 to
1.05 or 1.07 things went sideways
did a restore to earlier and things were back up.
now on ver 10
